name: Rust (wasm32-unknown-unknown)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add target wasm32-unknown-unknown
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --verbose --target=wasm32-unknown-unknown
