name: Rust (thumbv7em-none-eabihf)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add target thumbv7em-none-eabihf
      run: rustup target add thumbv7em-none-eabihf
    - name: Build
      run: cargo build --verbose --target=thumbv7em-none-eabihf
